background #0e1514
foreground #dde4e2

selection_background #324b49
selection_foreground #cce8e4

cursor #81d5ce
cursor_text_color background

# Black / Surface Container Variants
color0 #2f3635
color8 #899391

# Red (Error)
color1 #ffb4ab
color9 #93000a

# Green
color2  #afc9e7
color10 #304962

# Yellow / Orange
color3  #b0ccc8
color11 #324b49

# Blue / Primary
color4  #81d5ce
color12 #00504c

# Magenta
color5  #006a65
color13 #afc9e7

# Cyan
color6  #3f4947
color14 #3f4947

# White / Light
color7  #bec9c7
color15 #dde4e2
