# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ae5b0cba-8314-468c-8efc-4174aeca6027";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/ae5b0cba-8314-468c-8efc-4174aeca6027";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
      neededForBoot = true;
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ae5b0cba-8314-468c-8efc-4174aeca6027";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/ae5b0cba-8314-468c-8efc-4174aeca6027";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F0C8-0C65";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  boot.initrd.systemd.services.rollback = {
    description = "Wipes btrfs root when booting";
    wantedBy = [ "initrd.target" ];

    after = [ "dev-disk-by\\x2duuid-ae5b0cba\\x2d8314\\x2d468c\\x2d8efc\\x2d4174aeca6027.device" ];
    before = [ "sysroot.mount" ];

    path = [ pkgs.btrfs-progs pkgs.coreutils pkgs.util-linux ];

    unitConfig.DefaultDependencies = "no";
    serviceConfig.Type = "oneshot";

    script = ''
      mkdir -p /mnt
      mount -o subvol=/ /dev/disk/by-uuid/ae5b0cba-8314-468c-8efc-4174aeca6027 /mnt

      cleanup() {
        echo "Unmounting /mnt"
        umount /mnt || true
      }
      trap cleanup EXIT

      if [ ! -e /mnt/root-blank ]; then
        echo "ERROR: Pristine snapshot /mnt/root-blank does not exist!"
        exit 1
      fi

      if [ -e /mnt/root ]; then
        echo "Found existing /root subvolume. Cleaning up..."

        btrfs subvolume list -o /mnt/root | while read -r f1 f2 f3 f4 f5 f6 f7 f8 f9; do
          echo "Deleting nested subvolume: /mnt/$f9"
          btrfs subvolume delete "/mnt/$f9"
        done

        echo "Deleting /root subvolume..."
        btrfs subvolume delete /mnt/root
      fi

      echo "Restoring pristine /root subvolume..."
      btrfs subvolume snapshot /mnt/root-blank /mnt/root
    '';
  };
}
