# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.kernelParams = [
    "amdgpu.ppfeaturemask=0xffffffff"
    "resume_offset=88155392"
    "amdgpu.mcbp=0"
    "iommu=pt"
  ];

  # The amdgpu driver doesn't manage the gpu temperature curve correctly and destroys the gpu
  # under high performance because it maintains the fans at
  # 50% load under 110 degrees. This script starts fans at high load with a continuous curve.
  systemd.services.amdgpu-fan-curve = {
    description = "AMD GPU Fan Curve Service";
    wantedBy = [ "graphical.target" ];
    after = [ "graphical.target" ];

    path = with pkgs; [ coreutils gnugrep gnused bash bc ];

    script = ''
    set +e

    HWMON_DIR=""
    for dir in /sys/class/drm/card1/device/hwmon/hwmon*; do
      if [ -d "$dir" ]; then
        HWMON_DIR="$dir"
        break
      fi
    done

    if [ -z "$HWMON_DIR" ]; then
      for dir in /sys/class/drm/card*/device/hwmon/hwmon*; do
        if [ -f "$dir/name" ] && [ "$(cat "$dir/name")" = "amdgpu" ]; then
          HWMON_DIR="$dir"
          break
        fi
      done
    fi

    if [ -z "$HWMON_DIR" ]; then
      echo "GPU Path invalid!"
      exit 1
    fi

    while true; do
      echo 1 > "$HWMON_DIR/pwm1_enable"
      if [ -f "$HWMON_DIR/temp1_input" ]; then
        TEMP=$(cat "$HWMON_DIR/temp1_input")
        X=$((TEMP / 1000))

        PWM_CALC=$(bc -l <<EOF
          x = $X
          p = (0.075 * (x^2)) - (2.82 * x) + 0.0
          scale = 0
          p / 1
EOF
        )

        # Clamping
        if [ "$PWM_CALC" -lt 50 ]; then
          PWM=50
        elif [ "$PWM_CALC" -gt 255 ]; then
          PWM=255
        else
          PWM=$PWM_CALC
        fi

        echo $PWM > "$HWMON_DIR/pwm1"
      fi
      sleep 2
    done
    '';

    serviceConfig = {
      Restart = "always";
      RestartSec = "5s";
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ae5b0cba-8314-468c-8efc-4174aeca6027";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/ae5b0cba-8314-468c-8efc-4174aeca6027";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
      neededForBoot = true;
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ae5b0cba-8314-468c-8efc-4174aeca6027";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/ae5b0cba-8314-468c-8efc-4174aeca6027";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F0C8-0C65";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ {
    device = "/persist/swapfile";
    size = 65536;
  } ];

  boot.resumeDevice = "/dev/disk/by-uuid/ae5b0cba-8314-468c-8efc-4174aeca6027";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  boot.initrd.systemd.services.rollback = {
    description = "Wipes btrfs root when booting";
    wantedBy = [ "initrd.target" ];

    after = [ "dev-disk-by\\x2duuid-ae5b0cba\\x2d8314\\x2d468c\\x2d8efc\\x2d4174aeca6027.device" ];
    before = [ "sysroot.mount" ];

    path = [ pkgs.btrfs-progs pkgs.coreutils pkgs.util-linux ];

    unitConfig.DefaultDependencies = "no";
    serviceConfig.Type = "oneshot";

    script = ''
      mkdir -p /mnt
      mount -o subvol=/ /dev/disk/by-uuid/ae5b0cba-8314-468c-8efc-4174aeca6027 /mnt

      cleanup() {
        echo "Unmounting /mnt"
        umount /mnt || true
      }
      trap cleanup EXIT

      if [ ! -e /mnt/root-blank ]; then
        echo "ERROR: Pristine snapshot /mnt/root-blank does not exist!"
        exit 1
      fi

      if [ -e /mnt/root ]; then
        echo "Found existing /root subvolume. Cleaning up..."

        btrfs subvolume list -o /mnt/root | while read -r f1 f2 f3 f4 f5 f6 f7 f8 f9; do
          echo "Deleting nested subvolume: /mnt/$f9"
          btrfs subvolume delete "/mnt/$f9"
        done

        echo "Deleting /root subvolume..."
        btrfs subvolume delete /mnt/root
      fi

      echo "Restoring pristine /root subvolume..."
      btrfs subvolume snapshot /mnt/root-blank /mnt/root
    '';
  };
}
